# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "WHOLE BEAST RAG | Fertilize Your Brain"
email: wbr@keishaperry.com
description: >- # this means to ignore newlines until "baseurl:"
  Whole Beast Rag is a quarterly online publication dedicated to writers, artists, and thinkers on the frontier of pop culture and critical thinking. We dabble in literature, interviews, supplements, translations and other transmissions.  
  Whole Beast Rag operated from January 2012 to November 2013. The idea will live on.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://reverent-knuth-ecb665.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /articles/:title  
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
